language: node_js
node_js:
- '4'
notifications:
  slack:
    secure: FSnsRjIDDiOZ5Uj8ANdOrxZaRT7tp1t/9B9NeY/OD6ka9AAI1YXynM2fKT+c+EckjpH4MYhdg3KWcMSRbpKTMPOJ2oz3mS70oxN2mv89+E11LmEOdDUekwUVgWw5oxfU0N38n58nFkTHXx6pG6W+LnxjR1JfQhZ5VHlwoYr+At53CLXpZc9p6j6hgn0uKr1e0sggN5Ggg5PiPHCw4UlaSwtT2vutynKdEsttDBQdv2mZMNCevUgp14xh3i5tptjpEGCCD+ODAsZW2H1zdlkyDogkq9272TW4b4Z6gXyaGo+LOaYsYfCdnudYtiq39G2apvtZhZ3vj9SPoKAdIwyZBg6peHyGC72os/3ZOdhbZzhpiWdoRLkUjqg3zandvy8RLh3Ko9qDRXOlI1b4VZ3dcSXk5eYHc1nRI/CUqkSczVYJdItuxV1k1M/9P6EP9Y4fjTMLHbkfPCmTPKwuJLDYBmESRp9IlKzWu9nfKwrZ1+EDUL19yxx0ZjQxsd0NgafPKs18SrKM9SBC+lh84T1iz3c661XRUPPddEZmjTNzzWlR2+0uuG2mAlwOpZWqUwrVvbi0SuIb76xrQV7UWmLJy54j/NaiUHKG1fwrgrzAAOKGF0ZUbGLdZzc1JBWq9UBNlbNY43fUAvKsjVgl/rzOrp3wUeofnd6CYa4/fcduwss=

